platform/x86: mlx-platform: Add missing dependencies
Resolve missing I2C dependency resulting in:

drivers/platform/x86/mlx-platform.o: In function `mlxplat_mlxcpld_verify_bus_topology':
drivers/platform/x86/mlx-platform.c:861: undefined reference to `i2c_get_adapter'
drivers/platform/x86/mlx-platform.c:863: undefined reference to `i2c_put_adapter'

Add additional explicit dependency on REGMAP and implicit dependencies
on I2C_MUX_MLXCPLD and MLXREG_HOTPLUG.

Signed-off-by: Darren Hart (VMware) <dvhart@infradead.org>